SET @a=(SELECT MIN(LAT_N) FROM STATION);
SET @b=(SELECT MAX(LAT_N) FROM STATION);
SET @c=(SELECT MIN(LONG_W) FROM STATION);
SET @d=(SELECT MAX(LONG_W) FROM STATION);

SELECT ROUND(SQRT(POW((@a-@b),2)+POW((@c-@d),2)),4);