SET @a=(SELECT MIN(LAT_N) FROM STATION);
SET @b=(SELECT MIN(LONG_W) FROM STATION);
SET @c=(SELECT MAX(LAT_N) FROM STATION);
SET @d=(SELECT MAX(LONG_W) FROM STATION);

SELECT ROUND(ABS(@a-@c)+ABS(@b-@d),4);